### ISSUE TITLE
market sell order not work properly

### ISSUE THREAD

**Issue by bjgomadai** [sanko/Finance-Robinhood#1]
this is for 0.19 version.

Most of times i placed the market sell order it will not execute successfully,the order always in "placed" status , i tried changed extended_hours to 0 or 1 or even removed the option but have the same result.

   my $order = Finance::Robinhood::Order->new(
                      account    => $account,
                      instrument => $instrument,
                      type       => 'market',
                      trigger       => 'immediate',
                      time_in_force => 'gfd',
                      side          => 'sell',
                      quantity      => $quantity
                      #extended_hours => 1
        );

**Comment by memo-code** [comment]
Are you sure this is not Robinhood issue? I noticed that if I place an order from the app after market is closed, sometimes order is not executed next day.

**Comment by bjgomadai** [comment]
i'm sure, so the issue is not only for after market, i have encountered many times when placed a market order in trade hours and the orders showed in "placed" but never run successfully.

**Comment by bjgomadai** [comment]
it's easy to reproduce the issue by placing an market order in trade hours.

**Comment by sanko** [comment]
Are these securities really low in price? Sub $1?

**Comment by bjgomadai** [comment]
Not low price stocks. most are above $25, anyone else report the same issue ? just want to see if this is common issue or something wrong on my side.

**Comment by sanko** [comment]
First I've heard of a problem but most people don't use market orders so it's hard to be sure. I was thinking, if we were talking pennystocks, the bid price (which is 15 minutes old) might be more than 5% off the current (last executed) price. Robinhood's collared market orders behave exactly the way you describe in that situation. They sit with their status as 'placed' until the price is back within that 5% range.

**Comment by bjgomadai** [comment]
Hmm,let me try sell stop order next week to see if have the same problem.thanks

**Comment by memo-code** [comment]
As far as I know, Robinhood doesn't allow to place a market order if you don't have the buying power for that security + 5%, so the order is executed right away after placing it. Is there a way that this is bypassed somehow with the code?

**Comment by sanko** [comment]
@memo-code Just use a limit order.

**Comment by bjgomadai** [comment]
So i just did the test today between trade hours 11:00 am -12:30 PST, i random select one stock AR and placed both sell market and sell stop order, both are just in status "placed" but never execute, for sell stop order the i choose a price is near the trade price but even the price changed bellow the stop price the order still show "placed".   bellow is my code for sell stop and sell market.  

sub sell_market {

my $instrument = $rh->instrument('AR');
 $quantity = 1;

my $order = Finance::Robinhood::Order-> new(
                      account    => $account,
                      instrument => $instrument,
                      type       => 'market',
                      trigger       => 'immediate',
                      time_in_force => 'gfd',
                      side          => 'sell',
                      quantity      => $quantity
                      #extended_hours => 1
                      );

}



sub sell_stop {

my $instrument = $rh->instrument('AR');
 $quantity = 1;

my $order = Finance::Robinhood::Order-> new(
                      account    => $account,
                      instrument => $instrument,
                      type       => 'market',
                      trigger       => 'stop',
                      time_in_force => 'gfd',
                      side          => 'sell',
                      stop_price => 20.94,
                      quantity      => $quantity
                      #extended_hours => 1
                       );

                   }

**Comment by bjgomadai** [comment]
you can have a test at that time to see if have the same issue.

**Comment by memo-code** [comment]
@bjgomadai  I haven't tried market sell, but I'm sure that stop loss works. For Stop loss, make sure that type is 'stop_loss', not 'market'.

**Comment by bjgomadai** [comment]
Thanks for point it out,seems It's different with document https://metacpan.org/pod/Finance::Robinhood::Order#type(-)  ,i will try type 'stop_loss' other than market.

**Comment by bjgomadai** [comment]
Got new error while use 'stop_loss', do you have example show the right command ?

Odd number of elements in anonymous hash at /home/perl5/perlbrew/perls/perl-5.14.4/lib/site_perl/5.14.4/Finance/Robinhood/Order.pm line 55

         eval{    $order = Finance::Robinhood::Order-> new(
                      account    => $account,
                      instrument => $instrument,
                      type       => 'stop_loss',
                      trigger       => 'stop',
                      time_in_force => 'gfd',
                      side          => 'sell',
                      stop_price => $sellprice,
                      quantity      => $qu
                      #extended_hours => 1
                      ); };

**Comment by sanko** [comment]
@bjgomadai stop_loss is not an order type.

**Comment by bjgomadai** [comment]
Will appreciate if you can provide an example right command, just confused by the comments.

I haven't tried market sell, but I'm sure that stop loss works. For Stop loss, make sure that type is 'stop_loss', not 'market'.

**Comment by sanko** [comment]
@bjgomadai The entire bottom half of Finance::Robinhood::Order is a cheat sheet for all sorts of orders.

**Comment by bjgomadai** [comment]
So this is back to start, anyway if it's only me have this issue then there might something wrong on my side, thanks for your time look into this.
